# Generated by Django 4.2.3 on 2023-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranditionalcolor',
            name='b_num',
            field=models.IntegerField(help_text='b값'),
        ),
        migrations.AlterField(
            model_name='tranditionalcolor',
            name='g_num',
            field=models.IntegerField(help_text='g값'),
        ),
        migrations.AlterField(
            model_name='tranditionalcolor',
            name='r_num',
            field=models.IntegerField(help_text='r값'),
        ),
    ]
