# Generated by Django 4.2.3 on 2023-07-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0002_alter_tranditionalcolor_b_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranditionalColor',
        ),
    ]
