# Generated by Django 4.2.3 on 2023-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranditionalcolor',
            name='cymk_code',
            field=models.CharField(help_text='cymk 코드', max_length=15),
        ),
    ]
