# Generated by Django 4.2.3 on 2023-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0005_alter_tranditionalcolor_cymk_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranditionalColorCategory',
            fields=[
                ('category_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
