# Generated by Django 4.2.3 on 2023-07-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0007_rename_b_num_tranditionalcolor_b값_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='b값',
            new_name='b_num',
        ),
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='카테고리 코드',
            new_name='category_code',
        ),
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='색깔 이름',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='cymk 코드',
            new_name='cymk_code',
        ),
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='g값',
            new_name='g_num',
        ),
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='r값',
            new_name='r_num',
        ),
        migrations.RenameField(
            model_name='tranditionalcolor',
            old_name='rgb 코드',
            new_name='rgb_code',
        ),
    ]
