# Generated by Django 4.2.3 on 2023-07-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0008_rename_b값_tranditionalcolor_b_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeList',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=100)),
                ('code_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CodeManage',
            fields=[
                ('code_subcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('code_subname', models.CharField(max_length=100)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rensyu.codelist')),
            ],
        ),
    ]
