# Generated by Django 4.2.3 on 2023-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0009_codelist_codemanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemanage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codemanage',
            name='code_subcode',
            field=models.CharField(max_length=4),
        ),
        migrations.AddConstraint(
            model_name='codemanage',
            constraint=models.UniqueConstraint(fields=('code', 'code_subcode'), name='CodeManage_constraints_1'),
        ),
    ]
