# Generated by Django 4.2.3 on 2023-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0010_codemanage_id_alter_codemanage_code_subcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemanage',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
