# Generated by Django 4.2.3 on 2023-07-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0011_alter_codemanage_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='codemanage',
            name='CodeManage_constraints_1',
        ),
    ]
