# Generated by Django 4.2.3 on 2023-07-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0013_codemanage_codemanage_constraints_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeList',
        ),
        migrations.DeleteModel(
            name='CodeManage',
        ),
    ]
