# Generated by Django 4.2.3 on 2023-07-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0015_codelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeList',
        ),
    ]
