# Generated by Django 4.2.3 on 2023-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0016_delete_codelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('code_name', models.CharField(max_length=100)),
                ('code_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
