# Generated by Django 4.2.3 on 2023-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0017_codelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelist',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
