# Generated by Django 4.2.3 on 2023-07-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rensyu', '0018_alter_codelist_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_subcode', models.CharField(max_length=4)),
                ('code_subname', models.CharField(max_length=100)),
                ('codelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rensyu.codelist')),
            ],
        ),
    ]
